export const CART_ADD_ITEM = "CART_ADD_ITEM" ;
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM " ;
export const ITEM_QTY_PLUS_ONE= "ITEM_QTY_PLUS_ONE" ;
export const ITEM_QTY_MINUS_ONE= "ITEM_QTY_MINUS_ONE" ;
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING" ;