export const USER_SIGNIN_FAILED = ' USER_SIGNIN_FAILED '
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'

export const USER_REGISTER_FAILED = ' USER_REGISTER_FAILED '
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'

export const USER_CHANGE_DETAILS_FAILED = ' USER_CHANGE_DETAILS_FAILED  '
export const USER_CHANGE_DETAILS_REQUEST = 'USER_CHANGE_DETAILS_REQUEST'
export const USER_CHANGE_DETAILS_SUCCESS = 'USER_CHANGE_DETAILS_SUCCESS'

